name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Enter image name'
        required: true
      image_version:
        description: 'Enter image version'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Parse Image Name and Version from Tag
        id: parse_tag
        run: |
          IMAGE_NAME="${{ github.event.inputs.image_name }}"
          if [ -z "${{ github.event.inputs.image_version }}" ]; then
            IMAGE_VERSION=$(date +%Y%m%d)
          else
            IMAGE_VERSION="${{ github.event.inputs.image_version }}"
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

      - name: Check if the Dockerfile exists
        run: |
          if [ ! -f "${{ env.IMAGE_NAME }}/Dockerfile" ]; then
            echo "Error: Cannot find Dockerfile in ${{ env.IMAGE_NAME }} directory."
            exit 1
          fi
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            docker.io/surenkid/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            docker.io/surenkid/${{ env.IMAGE_NAME }}:latest
          file: ${{ env.IMAGE_NAME }}/Dockerfile
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
